# Generated by Django 2.2.6 on 2019-10-17 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idOpcion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('fechaDeNacimiento', models.DateField(default=datetime.date.today)),
                ('ocupacion', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('numeroCelular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('idPsicologo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idRespuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Opcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Paciente',
            fields=[
                ('idPregunta_Paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Paciente')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='idRespuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Respuesta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='idPsicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Psicologo'),
        ),
        migrations.CreateModel(
            name='Opcion_Pregunta',
            fields=[
                ('idOpcion_Pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Opcion')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('idHistoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('prediccion', models.CharField(max_length=50)),
                ('idPregunta_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Pregunta_Paciente')),
                ('idPsicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_app.Psicologo')),
            ],
        ),
    ]
