# Generated by Django 2.2.6 on 2019-10-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historia',
            name='prediccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numeroCelular',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='idRespuesta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='software_app.Respuesta'),
        ),
    ]
