# Generated by Django 2.2.6 on 2019-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0007_auto_20191019_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion_pregunta',
            name='idOpcion',
        ),
        migrations.RemoveField(
            model_name='opcion_pregunta',
            name='idPregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='idOpcion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='idRespuesta',
        ),
        migrations.AddField(
            model_name='pregunta_paciente',
            name='respuesta',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Opcion_Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
