# Generated by Django 2.2.6 on 2019-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0009_auto_20191107_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('idContador', models.IntegerField(primary_key=True, serialize=False)),
                ('contadorHistorias', models.IntegerField()),
                ('contadorPregunta_Paciente', models.ImageField(upload_to='')),
            ],
        ),
    ]
