# Generated by Django 2.2.6 on 2019-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0010_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contador',
            name='contadorPregunta_Paciente',
            field=models.IntegerField(),
        ),
    ]
